name: Deploy Voilà App

on:
  push:
    branches:
      - main  # Cambia por la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'  # Asegúrate de que sea la versión correcta de Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create GCP Service Account JSON
      run: |
        echo "$GCP_SERVICE_ACCOUNT" > $HOME/gcp_key.json
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Authenticate Earth Engine
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp_key.json"
        python -c "import ee; ee.Initialize()"

    - name: Run Voilà
      run: |
        voila --port=0