name: Deploy Voila app to GitHub Pages

on:
  push:
    branches:
      - main  # Se activará cuando hagas push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variable for GCP service account
        run: echo "GCP_SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV

      - name: Run Voilà app
        run: voila AguaTierra.ipynb --no-browser --port=8888 --Voila.tornado_settings="{'headers': {'Content-Security-Policy': ''}}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Cambia esto a la ruta de tu carpeta estática si la tienes (p.ej., ./docs)

