name: Deploy to Binder

on:
  push:
    branches:
      - main  # Cambia por la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment variable
        run: |
          echo "GCP_SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV

      - name: Launch Voilà
        run: voila --port=8888 --no-browser --enable_nbextensions=True --show_tracebacks=True
