name: Run Earth Engine Script

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # O la versión que necesites

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up GEE credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > service_account.json



