name: CI/CD for my project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set environment variable for GCP service account
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        echo "GCP_SERVICE_ACCOUNT is set"
        echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > credentials.json



